# Generated by Django 5.2.1 on 2025-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Completed'), ('f', 'Failed')], max_length=1),
        ),
    ]
