# Generated by Django 5.2.1 on 2025-07-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_restaurant_alter_orderitem_order'),
        ('restraunts', '0002_remove_restuarent_owner_restaurant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restuarent',
        ),
    ]
